### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by brosner**
While in search of a library to bind Python and duktape, I came across a couple, but found this one to be the one I liked the most. It hasn't been maintained for a while so I decided to fork it and start making fixes and improvements.

This PR is largely to gauge what kind of involvement you want to have. I am happy to continue making fixes, but for me to be more productive I'd really like to change the direction of styling in the code.

@abe-winter do you plan on maintaining this library or can I take ownership?

### CODE REVIEW

**Comment by abe-winter** [comment]
@brosner glad this library is getting some use, thanks for taking this on.
If you want the project, it's yours. Let me know if you want it transfered to your account. You can have the [pypi name](https://pypi.python.org/pypi/duktape) as well if interested.

**Comment by brosner** [comment]
@abe-winter I would love to take over. I think my account is ready for the transfer ownership. Go ahead and do that. Yes, please do add me on PyPI. I am brosner there too.

**Comment by abe-winter** [comment]
@brosner I'm getting 'brosner already has a repository in the abe-winter/duktape-py network' when I try to transfer -- I think you have to delete your fork.

**Comment by brosner** [comment]
@abe-winter ah, renaming it doesn't work. I've deleted it. Give it another go. Thanks!

**Comment by brosner** [comment]
Thank you @abe-winter! I will do the project proud :-)

**Comment by abe-winter** [comment]
@brosner I've added you as an owner to the pypi package. can you confirm that's working by deleting `amwinter` (me) from the package?

**Comment by brosner** [comment]
@abe-winter confirmed. I am all set. Now I am going to get coding :-)

**Pull request merged**
